// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbyxzatdmlynflemwqjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJieXh6YXRkbWx5bmZsZW13cWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Njk2MjIsImV4cCI6MjA3MjU0NTYyMn0.6r3lNwFFtAcUU_J8inQQsUPVhc366FLw-zIU_qcguww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});